plugins {
    id 'dev.kikugie.loom-back-compat'
    id 'me.modmuss50.mod-publish-plugin' version "2.0.1"
}

version = "${property("mod.version")}+${sc.current.version}"
base.archivesName = property("mod.id") as String

repositories {
    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${sc.current.version}"
    loomx.applyMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${property("deps.fabric_loader")}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${property("deps.fabric_api")}"

    implementation "net.kyori:adventure-api:${property("deps.adventure")}"
    implementation "net.kyori:adventure-text-minimessage:${property("deps.adventure")}"
    modImplementation "net.kyori:adventure-platform-fabric:${property("deps.adventure_fabric")}"

    modImplementation "dev.isxander:yet-another-config-lib:${property("deps.yacl")}"

    modImplementation "com.terraformersmc:modmenu:${property("deps.modmenu")}"

    implementation include("com.squareup.okhttp3:okhttp:${property("deps.okhttp")}")
    implementation include("com.squareup.okio:okio:${property("deps.okio")}")
    implementation "net.fabricmc:fabric-language-kotlin:${property("deps.fabric_kotlin")}"

    implementation "com.google.code.gson:gson:${property("deps.gson")}"
}

def props = [
        "id" : property("mod.id"),
        "version" : property("mod.version"),
        "name" : property("mod.name"),
        "minecraft" : property("mod.mc_compat"),
        "fabric_loader" : property("deps.fabric_loader")
]

processResources {
    inputs.properties(props)

    filesMatching("fabric.mod.json") {
        expand(props)
    }
}

def requiredJava = sc.current.parsed.matches('<=1.21.11') ? JavaVersion.VERSION_21 : JavaVersion.VERSION_25

java {
    targetCompatibility = requiredJava
    sourceCompatibility = requiredJava
}

def compatibleVersions = (sc.properties.rawOrNull("mod", "mc_releases") as List).collect { it.toString() }

publishMods {
    file = jar.archiveFile
    changelog = "Changelog"
    type = STABLE
    modLoaders.add("fabric")

    displayName = "${property("mod.name")} ${version}"

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = "alaQKApY"
        minecraftVersions = compatibleVersions

        requires("fabric-api")
        requires("adventure-platform-mod")
        requires("yacl")
        requires("fabric-language-kotlin")
        optional("modmenu")
    }

    github {
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        repository = "yazilie/FancyName"
        commitish = "stonecutter"
    }
}
